### ISSUE TITLE
Support sorting by column

### ISSUE THREAD

**Issue by mathstuf** [nbedos/cistern#11]
The default view shows older pipelines first. We have schedules that trigger builds nightly on our CI, so newer builds end up at the bottom of the view right now.

**Comment by nbedos** [comment]
Yes, this is planned too.

**Comment by nbedos** [comment]
@mathstuf Would you mind giving a try to https://github.com/nbedos/cistern/releases/tag/0.2.0dev5 please ?
It contains a fix for this issue as well as a couple of other changes.

**Comment by mathstuf** [comment]
Thanks! It works for top-level items, but I'm not seeing sorting applied to children. Example snippet:

```
REF     PIPELINE  TYPE  STATE    STARTED▼     DURATION  NAME                                 URL 
…
master   #156560  S     passed   Jan 8 00:06   528m10s   └── test                            https://gitlab.kitware.com/utils/rust-ghostflow/pipelines/156560  
master   #156560  J     passed   Jan 8 00:16     2m06s       ├── test:cargo-minimum          https://gitlab.kitware.com/utils/rust-ghostflow/-/jobs/4755936    
master   #156560  J     passed   Jan 8 00:19     1m59s       ├── test:cargo-stable           https://gitlab.kitware.com/utils/rust-ghostflow/-/jobs/4755937    
master   #156560  J     passed   Jan 8 00:06     4m11s       ├── test:cargo-tarpaulin        https://gitlab.kitware.com/utils/rust-ghostflow/-/jobs/4755938    
master   #156560  J     passed   Jan 8 00:21     1m44s       ├── test:cargo-nightly          https://gitlab.kitware.com/utils/rust-ghostflow/-/jobs/4755939    
master   #156560  J     passed   Jan 8 08:52     2m32s       └── test:git-master             https://gitlab.kitware.com/utils/rust-ghostflow/-/jobs/4755940  
```

**Comment by nbedos** [comment]
You're right, it should also work on children. I'll look into it.

**Comment by nbedos** [comment]
Here is a new pre-release with recursive sorting of stages, jobs and tasks: https://github.com/nbedos/cistern/releases/tag/0.2.0dev6

It was a bit tricky to get right for columns that may contains null values but I think it turned out ok. Let me know what you think.

**Comment by mathstuf** [comment]
That looks to be working well. Thanks!

**Comment by nbedos** [comment]
Great! I've merged the changes into `master`.
