### ISSUE TITLE
Add support for Azure Pipelines

### ISSUE THREAD

**Issue by Cadair** [nbedos/cistern#12]
This project is awesome, but we have moved a set of our builds to Azure Pipelines, would be great to add support for that :smile:

**Comment by nbedos** [comment]
It's already here, just add the following section to your configuration file and set the API token:
```
### AZURE DEVOPS ###
[[providers.azure]]
# Name shown by cistern for this provider
# (optional, string, default: "azure")
name = "azure"

# Azure API token (optional, string)
# Azure token management is done at https://dev.azure.com/ via
# the user settings menu
token = ""
``

**Comment by Cadair** [comment]
Awesome! Thanks!
