### ISSUE TITLE
Collapse subtrees on success

### ISSUE THREAD

**Issue by Cadair** [nbedos/cistern#18]
Currently if you have a large mutli-step matrix there can be a lot of lines of output. If all the steps of a job complete it would be nice if they could collapse down to just the name of the job so that there are fewer lines and it's easier to see what is still running or failed.

**Comment by nbedos** [comment]
Thanks for the suggestion, I see how that could be useful. I'll look into it.

**Comment by nbedos** [comment]
I made changes regarding this issue on the following branch: https://github.com/nbedos/cistern/tree/feature/status_changes

Automatically collapsing a step when the state changes to "passed" can now be enabled by setting the following settings in the configuration file:
 ```toml
autocollapse.job = true
autocollapse.stage = true
autocollapse.pipeline = true
```

Could you please test these changes and let me know if they work as expected?

**Comment by Cadair** [comment]
I tried this out on that branch, and despite adding:
```
[autocollapse]                                                                  
job = true                                                                      
stage = true                                                                    
pipeline = true
```

to my config file, when I ran `cistern` in the cistern repo I get:

![image](https://user-images.githubusercontent.com/1391051/73372262-d8f68a00-42ae-11ea-8e6a-baa5f43d71e5.png)

**Comment by nbedos** [comment]
Oh, my bad, I forgot to test this on finished pipelines. I just pushed new changes to the same branch, it should be fixed now.

**Comment by Cadair** [comment]
This seems to work nicely! I will keep testing it over the next few days :)

**Comment by Cadair** [comment]
I noticed another thing which I think is a bug, or at least a difference in behaviour between circle and Azure.

If I have 

```
autocollapse]                                                                  
job = false                                                                      
stage = true                                                                    
pipeline = true
```

I see this:

![Screenshot_20200129_181400](https://user-images.githubusercontent.com/1391051/73384667-98edd200-42c3-11ea-963d-4a8b15463c25.png)

Where the circleci builds are collapsing as I expect, but the azure ones aren't.

If I have

```
autocollapse]                                                                  
job = true                                                                      
stage = true                                                                    
pipeline = false
```

In my config I see this:

![Screenshot_20200129_182010](https://user-images.githubusercontent.com/1391051/73384854-01d54a00-42c4-11ea-8d7d-460912925bd7.png)

where the azure jobs are collapsing as I expect but the circleci ones aren't!

**Comment by Cadair** [comment]
(Also relatedly, I would love a key to toggle the collapsed state of a row, maybe tab?)

**Comment by nbedos** [comment]
Circle CI builds have the type "Pipeline" in `cistern` (you can see it in your screenshots, the column TYPE indicates "P" (pipeline) , not "J" (job)) so the behavior you're describing is consistent with your configuration. However I think you're right that they are jobs, not pipelines so I changed their type. In your first example the Circle CI build should not be collapsed anymore, and in the second example it should now be collapsed.

> Also relatedly, I would love a key to toggle the collapsed state of a row, maybe tab?

Good idea, I just added it.

Both changes are available on the same branch as previously: https://github.com/nbedos/cistern/commits/feature/status_changes

**Comment by Cadair** [comment]
:heart_eyes: It seems to be working great! Thanks so much!

**Comment by nbedos** [comment]
You're welcome! I've just merged my changes in `master` and so I'm closing this now. If something's wrong let me know and I'll reopen the issue.
