### ISSUE TITLE
Expand git urls using `git remote get-url`

### ISSUE THREAD

**Issue by mathstuf** [nbedos/cistern#7]
I use `insteadOf` settings for all of my repositories to ensure that I clone over HTTPS, but push over SSH. It seems that `citop` is not expanding these.

**Comment by mathstuf** [comment]
Glancing at the `go-git` docs, it seems to be a limitation that isn't supported in the library at all. I've filed an issue for the library (linked above).

**Comment by nbedos** [comment]
Thanks for reporting this and filing the issue for `go-git`. Until this gets fixed I'll probably call the local `git` executable to do the expansion. I don't have time to implement this right now but I'll work on it next week.

**Comment by nbedos** [comment]
There is a fix for this on `master`. I also made a pre-release with pre-built binaries: https://github.com/nbedos/cistern/releases/tag/0.2.0dev0

Let me know if it fixes the issue or not.

**Comment by mathstuf** [comment]
This seems to fix it. Thanks!
