### ISSUE TITLE
Look up BROWSER in PATH

### ISSUE THREAD

**Issue by mathstuf** [nbedos/cistern#8]
Using `BROWSER=firefox` fails, probably because `PATH` lookup isn't being done for the setting.

**Comment by nbedos** [comment]
Thanks for reporting this. Yes, you're right, there is no PATH lookup. I don't have time to take care of this right now but I should be able to fix it by the end of next week.

**Comment by nbedos** [comment]
There is a fix for this on `master`. I also made a pre-release with pre-built binaries: https://github.com/nbedos/cistern/releases/tag/0.2.0dev0

Let me know if it fixed the issue or not.

**Comment by mathstuf** [comment]
That looks to work, thanks!
